-- Create a table to store the master timetable structure
create table if not exists timetable_metadata (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default structure if not exists
insert into timetable_metadata (key, value)
values (
  'timetable_structure',
  '[
    {"start": "09:00", "end": "10:00", "type": "class"},
    {"start": "10:00", "end": "11:00", "type": "class"},
    {"start": "11:00", "end": "11:10", "type": "break", "label": "Short Break"},
    {"start": "11:10", "end": "12:10", "type": "class"},
    {"start": "12:10", "end": "13:00", "type": "break", "label": "Lunch Break"},
    {"start": "13:00", "end": "14:00", "type": "class"},
    {"start": "14:00", "end": "15:00", "type": "class"}
  ]'::jsonb
) on conflict (key) do nothing;

-- Enable RLS
alter table timetable_metadata enable row level security;

-- Policy: Everyone can read
create policy "Public Read Access"
  on timetable_metadata for select
  using (true);

-- Policy: Only Authenticated Users (Admins) can update
create policy "Authenticated Update Access"
  on timetable_metadata for update
  using (auth.role() = 'authenticated');

create policy "Authenticated Insert Access"
  on timetable_metadata for insert
  with check (auth.role() = 'authenticated');
