-- Seed file for KB Articles per Faculty

INSERT INTO "public"."kb_articles" ("title", "slug", "content", "category", "author_id") VALUES
-- Faculty: SITA LEELA MANAS JAGANNATH (CSE)
('Introduction to Object-Oriented Programming', 'intro-to-oop-manas', 'Object-Oriented Programming (OOP) is a programming paradigm based on the concept of "objects", which can contain data and code. The data is in the form of fields, and the code is in the form of procedures. The four pillars of OOP are Abstraction, Encapsulation, Inheritance, and Polymorphism. Abstraction hides complex reality while exposing only the necessary parts. Encapsulation restricts direct access to an object''s components. Inheritance allows a class to acquire the properties of another class. Polymorphism allows methods to perform different behaviors based on the object it acts upon. Mastering these principles allows developers to build scalable and modular software.', 'Academic', '0f5c2ff7-b676-41d6-90b4-6be2b47057ca'),
('Advanced Data Structures and Algorithms', 'adv-data-structures-algos-manas', 'Understanding complex data structures such as AVL Trees, Red-Black Trees, Heaps, and Graphs is crucial for developing highly efficient applications. Graphs represent networks and are used heavily in mapping algorithms, social networks, and routing protocols. Algorithms like Dijkstra''s, Bellman-Ford, and A* Search find the shortest paths within these graphs. The efficiency of these algorithms is typically measured using Big-O notation, which categorizes algorithms according to how their run time or space requirements grow as the input size grows.', 'Academic', '0f5c2ff7-b676-41d6-90b4-6be2b47057ca'),
('Operating System Concepts: Process Management', 'os-process-management-manas', 'Process Management is a fundamental concept in an Operating System (OS). A process is essentially a program in execution. The OS is responsible for allocating resources such as CPU time, memory, and I/O devices to processes. Process scheduling algorithms like Round Robin, Shortest Job First (SJF), and First-Come, First-Served (FCFS) determine the order in which processes execute. Additionally, concepts like inter-process communication (IPC), deadlocks, and multithreading are critical for ensuring that modern multitasking systems run smoothly without conflicts.', 'Academic', '0f5c2ff7-b676-41d6-90b4-6be2b47057ca'),
('Computer Networks: The OSI Model', 'computer-networks-osi-model-manas', 'The Open Systems Interconnection (OSI) model conceptualizes how different software and hardware components involved in a network communication should divide labor and interact with one another. It consists of seven layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application. The Physical layer handles the raw bit stream transmission over physical mediums. The Transport layer, home to TCP and UDP protocols, ensures reliable data transfer. Finally, the Application layer provides network services directly to end-user applications.', 'Academic', '0f5c2ff7-b676-41d6-90b4-6be2b47057ca'),

-- Faculty: Bhavana Yelagandala (CSE)
('Fundamentals of Machine Learning', 'fundamentals-of-machine-learning-bhavana', 'Machine Learning (ML) focuses on the development of algorithms that can learn from and make predictions on data. It is broadly categorized into Supervised Learning, Unsupervised Learning, and Reinforcement Learning. Supervised learning algorithms, such as Linear Regression and Support Vector Machines, learn from labeled training data. Unsupervised learning models, like K-Means clustering, find patterns in unlabeled data. Reinforcement learning relies on an agent interacting with an environment to maximize a reward signal.', 'Academic', '47528f2b-9e17-47d7-82d1-b6edeee9145b'),
('Deep Learning and Neural Networks', 'deep-learning-neural-networks-bhavana', 'Deep Learning is a subset of Machine Learning based on Artificial Neural Networks with multiple layers (deep architectures). These networks attempt to simulate the behavior of the human brain to "learn" from large amounts of data. Convolutional Neural Networks (CNNs) are primarily used for image recognition and processing, while Recurrent Neural Networks (RNNs) and Transformers are dominant in Natural Language Processing and sequential data analysis. Training these massive networks requires extensive computational power, typically utilizing GPUs.', 'Academic', '47528f2b-9e17-47d7-82d1-b6edeee9145b'),
('Natural Language Processing: Text Analytics', 'nlp-text-analytics-bhavana', 'Natural Language Processing (NLP) bridges the gap between human communication and computer understanding. Text analytics involves converting unstructured text into structured data. Key techniques include tokenization, stemming, lemmatization, and part-of-speech tagging. More advanced paradigms use word embeddings like Word2Vec and state-of-the-art transformer models like BERT and GPT. These models allow for sophisticated applications including sentiment analysis, machine translation, and interactive chatbots.', 'Academic', '47528f2b-9e17-47d7-82d1-b6edeee9145b'),
('Reinforcement Learning Strategies', 'reinforcement-learning-strategies-bhavana', 'Reinforcement learning revolves around training a software agent to make a sequence of decisions in an uncertain, potentially complex environment. The agent evaluates states and takes actions that maximize cumulative rewards over time. Concepts like the Markov Decision Process (MDP), Q-Learning, and Policy Gradients form the theoretical backbone. Applications range extensively from mastering complex board games like Go and Chess to autonomous driving and robotic motor control.', 'Academic', '47528f2b-9e17-47d7-82d1-b6edeee9145b'),

-- Faculty: Usha Vemireddy (CSE)
('Modern Web Development Architectures', 'modern-web-dev-architectures-usha', 'Modern web development relies heavily on decoupling the frontend from the backend, commonly utilizing architectures like Single Page Applications (SPAs). Frameworks such as React, Vue, and Angular allow developers to build dynamic, fast, and interactive user interfaces. Backend services are increasingly shifting towards microservices architectures and serverless functions to ensure high availability and horizontal scaling. Adopting strict CI/CD pipelines guarantees seamless software delivery.', 'Academic', 'a0761a83-78fd-4f4c-bf60-f7452c8ea89a'),
('React: State Management and Hooks', 'react-state-management-hooks-usha', 'React has revolutionized frontend engineering with its component-based architecture. State management is crucial for maintaining data consistency across highly complex UI components. While robust libraries like Redux or Zustand manage global states, React Hooks provide a powerful native mechanism. Hooks like useState and useEffect allow developers to tap into state and lifecycle features from functional components, promoting cleaner, more intuitive, and highly reusable code.', 'Academic', 'a0761a83-78fd-4f4c-bf60-f7452c8ea89a'),
('Node.js and Event-Driven Architecture', 'node-js-event-driven-architecture-usha', 'Node.js enables developers to use JavaScript to write server-side command-line tools and networking applications. Built on Google Chrome''s V8 JavaScript engine, it boasts an asynchronous, event-driven architecture. This single-threaded event loop design makes Node.js incredibly efficient and highly scalable, especially for I/O bound operations and real-time applications such as live chat engines and video streaming platforms.', 'Academic', 'a0761a83-78fd-4f4c-bf60-f7452c8ea89a'),
('Cloud Computing: Serverless vs Containers', 'cloud-computing-serverless-containers-usha', 'Cloud computing paradigms have shifted dramatically towards Serverless and containerized deployments. Docker and Kubernetes dominate container orchestration, offering portable and consistent environments across multiple deployment stages. Conversely, Serverless computing (like AWS Lambda) abstracts away infrastructure completely, enabling developers to simply execute functions on-demand while only paying for strict execution time. Choosing between them depends on cost, control, and architectural requirements.', 'Academic', 'a0761a83-78fd-4f4c-bf60-f7452c8ea89a'),

-- Faculty: UPLANCHIWAR SREEJA (CSE)
('Cybersecurity: Principles of InfoSec', 'cybersecurity-principles-infosec-sreeja', 'The foundation of Information Security revolves around the CIA triad: Confidentiality, Integrity, and Availability. Confidentiality ensures that sensitive data is accessed only by authorized parties. Integrity protects data from unauthorized modifications. Availability ensures that systems and data remain accessible to authorized users when needed. Modern cybersecurity architectures require layered defense mechanisms (Defense in Depth), spanning from perimeter firewalls and intrusion detection systems to end-to-end encryption.', 'Academic', 'abec755b-08a1-4940-bb1b-95f3f28dc804'),
('Cryptography: Symmetric vs Asymmetric', 'cryptography-symmetric-asymmetric-sreeja', 'Cryptography is the science of secure communication. Symmetric encryption relies on a single shared key to both encrypt and decrypt data; it is extremely fast and suitable for bulk data (e.g., AES). Asymmetric encryption, however, uses a mathematical key pair: a public key for encryption and a private key for decryption (e.g., RSA, ECC). While slower computational-wise, asymmetric keys solve the critical challenge of secure key distribution over untrusted networks.', 'Academic', 'abec755b-08a1-4940-bb1b-95f3f28dc804'),
('Understanding Blockchain Technology', 'understanding-blockchain-tech-sreeja', 'Blockchain is a decentralized and distributed digital ledger that operates securely across a peer-to-peer network. Once recorded, the data in any given block cannot be altered retroactively without the alteration of all subsequent blocks, which requires network consensus. This immutability guarantees extreme cryptographic fidelity. Blockchains are the underlying architecture for cryptocurrencies, but their use extends to secure supply chain tracking, immutable medical records, and smart contracts.', 'Academic', 'abec755b-08a1-4940-bb1b-95f3f28dc804'),
('Ethical Hacking and Penetration Testing', 'ethical-hacking-pen-testing-sreeja', 'Ethical hacking involves authorized attempts to bypass system security in order to identify potential data breaches and vulnerabilities. Penetration testing systematically simulates cyberattacks using distinct methodologies: Reconnaissance, Scanning, Gaining Access, Maintaining Access, and Analysis. Testers use automated tools and manual exploits to probe networks, applications, and operating systems, allowing organizations to patch vulnerabilities proactively before malicious actors can exploit them.', 'Academic', 'abec755b-08a1-4940-bb1b-95f3f28dc804'),

-- Faculty: Chris (CSE)
('Database Management: SQL and Relational Algebra', 'db-management-sql-relational-algebra-chris', 'Relational Database Management Systems (RDBMS), relying heavily on Structured Query Language (SQL), maintain data within specifically structured tables. Relational algebra provides the theoretical foundation for these queries through operators like Selection, Projection, Union, and Join. Normalization—eliminating data redundancy and dependency anomalies—is critical during schema design. Robust RDBMS platforms like PostgreSQL enforce strict ACID properties, ensuring reliable, atomic, and consistent transaction processing.', 'Academic', 'c88429ef-f629-4b10-86b1-5f6b1568f8fa'),
('NoSQL Databases: When to use them', 'nosql-databases-when-to-use-chris', 'Unlike standard relational databases, NoSQL databases handle unstructured or semi-structured data with flexible schemas. They group into document stores (MongoDB), key-value stores (Redis), wide-column stores (Cassandra), and graph databases (Neo4j). NoSQL is advantageous for massive horizontal scaling, real-time web applications, and large dataset ingestion where strict ACID compliance is willingly traded for eventually consistent, high-availability data architectures.', 'Academic', 'c88429ef-f629-4b10-86b1-5f6b1568f8fa'),
('Data Engineering: ETL Pipelines', 'data-engineering-etl-pipelines-chris', 'Data Engineering focuses heavily on architecting systems for collecting, storing, and analyzing large volumes of data. Extract, Transform, Load (ETL) pipelines form the backbone of these architectures. Data is extracted from discrete sources, transformed into analytics-ready formats (cleansed, aggregated, joined), and subsequently loaded into an Enterprise Data Warehouse or Data Lake. Modern tools like Apache Airflow provide the complex orchestration required to build resilient, distributed pipelines.', 'Academic', 'c88429ef-f629-4b10-86b1-5f6b1568f8fa'),
('Advanced PostgreSQL Architectures', 'advanced-postgresql-architectures-chris', 'PostgreSQL is arguably the most advanced open-source relational database in existence. Mastering it entails understanding its intricate MVCC (Multi-Version Concurrency Control) mechanism, which mitigates database locking constraints. In addition, mastering indexing strategies encompassing B-Trees, Hash, GiST, and GIN significantly accelerates querying. Developers must also utilize functional configurations such as native JSONB support to bridge the gap between relational integrity and document-store flexibility.', 'Academic', 'c88429ef-f629-4b10-86b1-5f6b1568f8fa'),

-- Faculty: John Doe (EEE)
('Power Systems and Grid Distribution', 'power-systems-grid-distribution-john', 'Modern power systems encompass the intricate generation, transmission, and distribution of electrical grid energy. Power is transmitted at extremely high voltages over long distances to minimize energy losses, relying on complex step-up and step-down transformer architectures. The integration of robust SCADA systems enables engineers to monitor grid telemetry continuously, preventing cascading failures and accommodating volatile load balancings inherent in smart grid implementations.', 'Academic', 'fcb15f0f-53d4-4c84-b536-5a8b90f8c47c'),
('Microprocessors and Embedded Systems', 'microprocessors-embedded-systems-john', 'Microprocessors serve as the computational brains of almost all modern electronic equipment. An Embedded System couples these physical microprocessors with highly specialized software to execute predefined tasks deterministically. Ranging from automotive engine management systems to household appliances, these systems require deep proficiency in real-time operating systems (RTOS) and an intricate understanding of hardware interrupts, memory mapping, and digital communication protocols like I2C, SPI, and UART.', 'Academic', 'fcb15f0f-53d4-4c84-b536-5a8b90f8c47c'),
('Circuit Theory and Network Analysis', 'circuit-theory-network-analysis-john', 'At the foundation of all electrical engineering exists classical circuit theory. Ohm''s Law and Kirchhoff''s Current and Voltage definitions act as the bedrock for evaluating complex topologies. Network analysis techniques such as Thevenin''s Theorem, Norton''s Theorem, and Superposition enable engineers to simplify labyrinthine circuits down to manageable mathematically equivalent matrices. Accurate transient analysis additionally permits engineers to predict operational safety limits during inductive and capacitive load fluctuations.', 'Academic', 'fcb15f0f-53d4-4c84-b536-5a8b90f8c47c'),
('Renewable Energy Integration', 'renewable-energy-integration-john', 'Renewable generation techniques — significantly photovoltaic solar arrays and high-capacity wind turbines — present unique challenges in electrical grid integration. Unlike classical synchronous generators, green power generation output fluctuates drastically with unpredictable weather patterns. Resolving this discrepancy requires sophisticated Power Electronic inverters, substantial grid-level battery storage, and advanced Maximum Power Point Tracking (MPPT) logic to align unpredictable DC input waves faithfully directly into the synchronous AC grid.', 'Academic', 'fcb15f0f-53d4-4c84-b536-5a8b90f8c47c');
